### ISSUE TITLE
Speech Presets no longer saving

### ISSUE THREAD

**Issue by PaulH74** [otakudaddy/smartstory_issue_tracker#2]
This bug / error has started occurring today (5/2/19).

Speech preset voices are not saving correctly (eg. Narrator, Anne, Simon, etc) and need to be re-created each time the story is loaded.

Please note: the actual voice settings (eg. male / female, pitch, speed, volume, etc) applied to each segment are correct and do not seem to be affected.

In the image below, the voice preset should show "Narrator":

![image](https://user-images.githubusercontent.com/21220682/52252629-89a9a200-2957-11e9-9543-877bcaf57d9b.png)

**Comment by otakudaddy** [comment]
Hi Paul,
Could you tell me which story it is happening in (is it all of them)? Under my own testing account I can't replicate this. Did you use the new delete preset feature before this started happening?
Cheers,
Charlie

**Comment by otakudaddy** [comment]
Just realised, that presets only save for individual projects - so a preset created in project a won't show up in project b... This might be unrelated to the bug, but I will make presets global

**Comment by otakudaddy** [comment]
Hi Paul,

I've found the problem and deployed a fix. Can you please confirm.
Cheers,
Charlie

**Comment by PaulH74** [comment]
Hi Charlie,

Thank you - this issue has been resolved.

Regards,
Paul

**Comment by otakudaddy** [comment]
Hi Paul,

I'm sure you noticed that the fix wiped existing presets - sorry about that.
I'll close the issue.

**Comment by PaulH74** [comment]
Hi Charlie,

I'm sorry to tell you this but the preset problem has re-occurred.  The presets were working fine for the past couple of hours this morning - I tested across multiple stories.  Not sure what, if anything has changed, but I've lost my saved presets again. 

As before, the settings themselves are not affected.

**Comment by otakudaddy** [comment]
Hi Paul,

I think what happened is that the fix only kicked in after you cleared the cache for the other issue and it just 'happened to work' before (i can see from my code how that's possible, but won't go into detail).
My last comment when I first closed this issue was that your existing presets would be wiped... so I think you're at that point now and it should work from now on. Sorry about having to recreate presets... the good news is that you only have to do it in one story for one segment (per preset) and any segment will recognise if they're identical to a preset and display as such. Hope this makes sense :)
Anyway, let me know how you go...
Cheers,
Charlie

**Comment by PaulH74** [comment]
Hi Charlie,

Yes it looks like the issue is resolved again.

Thank you for sorting it out - I'll keep an eye on it as I continue to build the stories and if there's any problem, I'll let you know.

Paul
